# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Peter J. Lu
email: plu@fas.harvard.edu
description: >- # this means to ignore newlines until "baseurl:"
  Peter J. Lu, post-doctoral research fellow in the Department of Physics and the School of Engineering and Applied Sciences at Harvard University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: peterjameslu
github_username:  peterlu

# Build settings
markdown: kramdown
# theme: minima
theme: jekyll-skeleton
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /:categories/:title:output_ext

# collections:
#   medieval_islamic_geometry:
#     output: true
#   soft-matter_and_colloid_physics:
#     output: true

plugins:
  - jekyll-seo-tag
  - jekyll/scholar
  - jekyll-polyglot

# languages: ["en", "it", "fr", "es", "zh", "ar", "tr"]
languages: ["en", "it"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "pdf", "assets"]
parallel_localization: true

scholar:
  bibliography_template: bib
  repository: pdf
  style: _data/science-plu.csl
#  style: chicago-note-bibliography
#  style: _data/apa-pdf.csl
